# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: glimmer-dsl-opal 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "glimmer-dsl-opal".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["AndyMaleh".freeze]
  s.date = "2020-07-02"
  s.description = "Glimmer DSL for Opal (Web GUI Adapter for Desktop Apps)".freeze
  s.email = "andy.am@gmail.com".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/glimmer-dsl-opal.rb",
    "lib/glimmer/data_binding/element_binding.rb",
    "lib/glimmer/data_binding/ext/observable_model.rb",
    "lib/glimmer/data_binding/list_selection_binding.rb",
    "lib/glimmer/data_binding/observable_element.rb",
    "lib/glimmer/data_binding/table_items_binding.rb",
    "lib/glimmer/dsl/opal/async_exec_expression.rb",
    "lib/glimmer/dsl/opal/bind_expression.rb",
    "lib/glimmer/dsl/opal/browser_expression.rb",
    "lib/glimmer/dsl/opal/button_expression.rb",
    "lib/glimmer/dsl/opal/column_properties_expression.rb",
    "lib/glimmer/dsl/opal/combo_expression.rb",
    "lib/glimmer/dsl/opal/combo_selection_data_binding_expression.rb",
    "lib/glimmer/dsl/opal/composite_expression.rb",
    "lib/glimmer/dsl/opal/data_binding_expression.rb",
    "lib/glimmer/dsl/opal/dsl.rb",
    "lib/glimmer/dsl/opal/grid_layout_expression.rb",
    "lib/glimmer/dsl/opal/label_expression.rb",
    "lib/glimmer/dsl/opal/layout_data_expression.rb",
    "lib/glimmer/dsl/opal/list_expression.rb",
    "lib/glimmer/dsl/opal/list_selection_data_binding_expression.rb",
    "lib/glimmer/dsl/opal/message_box_expression.rb",
    "lib/glimmer/dsl/opal/observe_expression.rb",
    "lib/glimmer/dsl/opal/property_expression.rb",
    "lib/glimmer/dsl/opal/shell_expression.rb",
    "lib/glimmer/dsl/opal/tab_folder_expression.rb",
    "lib/glimmer/dsl/opal/tab_item_expression.rb",
    "lib/glimmer/dsl/opal/table_column_expression.rb",
    "lib/glimmer/dsl/opal/table_expression.rb",
    "lib/glimmer/dsl/opal/table_items_data_binding_expression.rb",
    "lib/glimmer/dsl/opal/text_expression.rb",
    "lib/glimmer/dsl/opal/widget_listener_expression.rb",
    "lib/glimmer/opal/display_proxy.rb",
    "lib/glimmer/opal/div_proxy.rb",
    "lib/glimmer/opal/document_proxy.rb",
    "lib/glimmer/opal/element_proxy.rb",
    "lib/glimmer/opal/event_listener_proxy.rb",
    "lib/glimmer/opal/grid_layout_proxy.rb",
    "lib/glimmer/opal/iframe_proxy.rb",
    "lib/glimmer/opal/input_proxy.rb",
    "lib/glimmer/opal/label_proxy.rb",
    "lib/glimmer/opal/layout_data_proxy.rb",
    "lib/glimmer/opal/list_proxy.rb",
    "lib/glimmer/opal/modal.rb",
    "lib/glimmer/opal/point.rb",
    "lib/glimmer/opal/property_owner.rb",
    "lib/glimmer/opal/select_proxy.rb",
    "lib/glimmer/opal/tab_folder.rb",
    "lib/glimmer/opal/tab_item.rb",
    "lib/glimmer/opal/table_column.rb",
    "lib/glimmer/opal/table_item.rb",
    "lib/glimmer/opal/table_proxy.rb",
    "lib/glimmer/swt/shell_proxy.rb",
    "lib/glimmer/swt/widget_proxy.rb",
    "lib/samples/elaborate/contact_manager.rb",
    "lib/samples/elaborate/contact_manager/contact.rb",
    "lib/samples/elaborate/contact_manager/contact_manager_presenter.rb",
    "lib/samples/elaborate/contact_manager/contact_repository.rb",
    "lib/samples/elaborate/launch",
    "lib/samples/elaborate/login.rb",
    "lib/samples/elaborate/tic_tac_toe.rb",
    "lib/samples/elaborate/tic_tac_toe/board.rb",
    "lib/samples/elaborate/tic_tac_toe/cell.rb",
    "lib/samples/hello/hello_browser.rb",
    "lib/samples/hello/hello_combo.rb",
    "lib/samples/hello/hello_computed.rb",
    "lib/samples/hello/hello_computed/contact.rb",
    "lib/samples/hello/hello_list_multi_selection.rb",
    "lib/samples/hello/hello_list_single_selection.rb",
    "lib/samples/hello/hello_tab.rb",
    "lib/samples/hello/hello_world.rb",
    "lib/samples/hello/launch",
    "lib/samples/launch"
  ]
  s.homepage = "http://github.com/AndyObtiva/glimmer-dsl-opal".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Glimmer DSL for Opal".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<delegate>.freeze, ["~> 0.1.0"])
    s.add_runtime_dependency(%q<glimmer>.freeze, ["~> 0.9.3"])
    s.add_development_dependency(%q<puts_debuggerer>.freeze, ["~> 0.8.1"])
    s.add_development_dependency(%q<rake>.freeze, [">= 10.1.0", "< 14.0.0"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 2.3.9", "< 3.0.0"])
    s.add_development_dependency(%q<rdoc>.freeze, [">= 6.2.1", "< 7.0.0"])
    s.add_development_dependency(%q<opal-rspec>.freeze, ["~> 0.8.0.alpha2"])
    s.add_development_dependency(%q<opal-async>.freeze, ["~> 1.1.0"])
    s.add_development_dependency(%q<opal-browser>.freeze, ["~> 0.2.0"])
    s.add_development_dependency(%q<glimmer-dsl-opal>.freeze, [">= 0"])
  else
    s.add_dependency(%q<delegate>.freeze, ["~> 0.1.0"])
    s.add_dependency(%q<glimmer>.freeze, ["~> 0.9.3"])
    s.add_dependency(%q<puts_debuggerer>.freeze, ["~> 0.8.1"])
    s.add_dependency(%q<rake>.freeze, [">= 10.1.0", "< 14.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 2.3.9", "< 3.0.0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 6.2.1", "< 7.0.0"])
    s.add_dependency(%q<opal-rspec>.freeze, ["~> 0.8.0.alpha2"])
    s.add_dependency(%q<opal-async>.freeze, ["~> 1.1.0"])
    s.add_dependency(%q<opal-browser>.freeze, ["~> 0.2.0"])
    s.add_dependency(%q<glimmer-dsl-opal>.freeze, [">= 0"])
  end
end

